/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase5;

import javax.swing.JOptionPane;

/**
 *
 * @author Lee Brandon
 */
public class Casi_CRUD extends javax.swing.JFrame {

    /**
     * Creates new form Casi_Crud
     */
    int numeros[];
    int indice;

    public Casi_CRUD() {
        initComponents();
        this.setLocationRelativeTo(null);
        indice = 0;
        numeros = new int[4];

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarB = new javax.swing.JButton();
        MostrarB = new javax.swing.JButton();
        NumeroT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        BuscarT = new javax.swing.JTextField();
        BuscarB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ModificarT = new javax.swing.JTextField();
        ModificarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INGRESE NUMERO");

        AgregarB.setBackground(new java.awt.Color(153, 153, 153));
        AgregarB.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        AgregarB.setForeground(new java.awt.Color(0, 0, 0));
        AgregarB.setText("AGREGAR");
        AgregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBActionPerformed(evt);
            }
        });

        MostrarB.setBackground(new java.awt.Color(153, 153, 153));
        MostrarB.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        MostrarB.setForeground(new java.awt.Color(0, 0, 0));
        MostrarB.setText("MOSTRAR");
        MostrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBActionPerformed(evt);
            }
        });

        NumeroT.setBackground(new java.awt.Color(204, 204, 204));
        NumeroT.setForeground(new java.awt.Color(0, 0, 0));
        NumeroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroTActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CASI CRUD");

        MostrarA.setColumns(20);
        MostrarA.setRows(5);
        jScrollPane1.setViewportView(MostrarA);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BUSCAR NUMERO");

        BuscarT.setBackground(new java.awt.Color(204, 204, 204));
        BuscarT.setForeground(new java.awt.Color(0, 0, 0));
        BuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTActionPerformed(evt);
            }
        });

        BuscarB.setBackground(new java.awt.Color(153, 153, 153));
        BuscarB.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        BuscarB.setForeground(new java.awt.Color(0, 0, 0));
        BuscarB.setText("BUSCAR");
        BuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("MODIFICAR POR");

        ModificarT.setBackground(new java.awt.Color(204, 204, 204));
        ModificarT.setForeground(new java.awt.Color(0, 0, 0));
        ModificarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTActionPerformed(evt);
            }
        });

        ModificarB.setBackground(new java.awt.Color(153, 153, 153));
        ModificarB.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        ModificarB.setForeground(new java.awt.Color(0, 0, 0));
        ModificarB.setText("MODIFICAR");
        ModificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(NumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AgregarB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MostrarB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BuscarB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ModificarB))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModificarT, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumeroT))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ModificarT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarB)
                    .addComponent(BuscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Agregar(int numero) {
        if (indice < numeros.length) {
            numeros[indice] = numero;
            indice++;
            NumeroT.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "< VECTOR LLENO >");
        }
    }

    public void Mostrar() {
        MostrarA.setText("");
        for (int numero : numeros) {
            MostrarA.append(numero + "\n");
        }
    }
    public void Modificar (int pos, int num){
        numeros[pos] = num;
        JOptionPane.showMessageDialog(null, "< MODIFICADO CORRECTAMENTE >");
    }

    private void AgregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBActionPerformed
        String texto = NumeroT.getText();
        if (!texto.equals("")) {
            int numero = Integer.parseInt(NumeroT.getText());
            Agregar(numero);
        } else {
            JOptionPane.showMessageDialog(null, "< ERROR: INGRESE UN NUMERO >");
        }
    }//GEN-LAST:event_AgregarBActionPerformed

    private void MostrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBActionPerformed
        Mostrar();
    }//GEN-LAST:event_MostrarBActionPerformed

    private void BuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTActionPerformed

    }//GEN-LAST:event_BuscarTActionPerformed

    private void BuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBActionPerformed
        int numero = Integer.parseInt(BuscarT.getText());
        if (buscar(numero)!=-1) {
            JOptionPane.showMessageDialog(null, "< NUMERO ENCONTRADO >");
        } else {
            JOptionPane.showMessageDialog(null, "< NUMERO NO ENCONTRADO >");
        }
    }//GEN-LAST:event_BuscarBActionPerformed

    private void NumeroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroTActionPerformed

    private void ModificarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarTActionPerformed

    private void ModificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBActionPerformed
        int buscado = Integer.parseInt(BuscarT.getText());
        int modificar = Integer.parseInt(ModificarT.getText());
        int posicion = buscar(buscado);
        if (posicion!=-1) {
            Modificar(posicion, modificar);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR AL MODIFICAR");
        }
    }//GEN-LAST:event_ModificarBActionPerformed
    public int buscar(int nbus) {
        for (int i = 0; i < numeros.length; i++) {
            if (numeros[i]==nbus) {
                return i;
            }
        }
        return -1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casi_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casi_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casi_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casi_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casi_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarB;
    private javax.swing.JButton BuscarB;
    private javax.swing.JTextField BuscarT;
    private javax.swing.JButton ModificarB;
    private javax.swing.JTextField ModificarT;
    private javax.swing.JTextArea MostrarA;
    private javax.swing.JButton MostrarB;
    private javax.swing.JTextField NumeroT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
