/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_netbeans;

/**
 *
 * @author Lee Brandon
 */
public class Ferreteria extends javax.swing.JFrame {

    /**
     * Creates new form Ferreteria
     */
    public static String nombre[] = new String[100];
    public static float precio[] = new float[100];
    public static int stock[] = new int[100];
    public static String marca[] = new String[100];
    public static String origen[] = new String[100];
    public static String categoría[] = new String[100];
    public static String código[] = new String[100];
    public static int garantía[] = new int[100];
    public static int cantidad = 0; // Pipipi
    public Ferreteria() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Aca en la clase principal
        
         //Aca agregue a los arrays, quize hacerlo sin poo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvendia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AgregarB = new javax.swing.JButton();
        EliminarB = new javax.swing.JButton();
        EditarB = new javax.swing.JButton();
        ListarB = new javax.swing.JButton();
        BuscarB = new javax.swing.JButton();
        add = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        seach = new javax.swing.JLabel();
        list = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvendia.setFont(new java.awt.Font("MV Boli", 1, 32)); // NOI18N
        Bienvendia.setForeground(new java.awt.Color(0, 0, 0));
        Bienvendia.setText("BIENVENIDO A \"CONEROS S.A.C\"");
        getContentPane().add(Bienvendia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 560, 30));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INDIQUE UNA OPCION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        AgregarB.setBackground(new java.awt.Color(153, 153, 255));
        AgregarB.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        AgregarB.setForeground(new java.awt.Color(0, 0, 0));
        AgregarB.setText("AGREGAR");
        AgregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 30));

        EliminarB.setBackground(new java.awt.Color(153, 153, 255));
        EliminarB.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        EliminarB.setForeground(new java.awt.Color(0, 0, 0));
        EliminarB.setText("ELIMINAR");
        EliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        EditarB.setBackground(new java.awt.Color(153, 153, 255));
        EditarB.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        EditarB.setForeground(new java.awt.Color(0, 0, 0));
        EditarB.setText("EDITAR");
        EditarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBActionPerformed(evt);
            }
        });
        getContentPane().add(EditarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, 30));

        ListarB.setBackground(new java.awt.Color(153, 153, 255));
        ListarB.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        ListarB.setForeground(new java.awt.Color(0, 0, 0));
        ListarB.setText("MOSTRAR");
        ListarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBActionPerformed(evt);
            }
        });
        getContentPane().add(ListarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 120, 30));

        BuscarB.setBackground(new java.awt.Color(153, 153, 255));
        BuscarB.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        BuscarB.setForeground(new java.awt.Color(0, 0, 0));
        BuscarB.setText("BUSCAR");
        BuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, 30));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/agregar-producto.png"))); // NOI18N
        add.setText("jLabel3");
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 120));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/eliminar-producto.png"))); // NOI18N
        delete.setText("jLabel2");
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, 120));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/editar-producto.png"))); // NOI18N
        update.setText("jLabel2");
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, 120));

        seach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/buscar-producto.png"))); // NOI18N
        seach.setText("jLabel2");
        getContentPane().add(seach, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, 120));

        list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/listar-producto.png"))); // NOI18N
        getContentPane().add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 120, -1));

        FONDO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lee Brandon\\Downloads\\FONDO FERRETERIA.png")); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AgregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBActionPerformed
        JFAgregar agregar = new JFAgregar();
        agregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarBActionPerformed

    private void EliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBActionPerformed
        JFEliminar eliminar = new JFEliminar();
        eliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarBActionPerformed

    private void EditarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBActionPerformed
        JFEditar editar = new JFEditar();
        editar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditarBActionPerformed

    private void BuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBActionPerformed
        JFBuscar buscar = new JFBuscar();
        buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarBActionPerformed

    private void ListarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBActionPerformed
        JFListar listar = new JFListar();
        listar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ferreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ferreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ferreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ferreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ferreteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarB;
    private javax.swing.JLabel Bienvendia;
    private javax.swing.JButton BuscarB;
    private javax.swing.JButton EditarB;
    private javax.swing.JButton EliminarB;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton ListarB;
    private javax.swing.JLabel add;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel list;
    private javax.swing.JLabel seach;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
