/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_netbeans;

import javax.swing.JOptionPane;

/**
 *
 * @author Lee Brandon
 */
public class JFBuscar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public JFBuscar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BuscarBB = new javax.swing.JButton();
        VOLVER = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MostrarT = new javax.swing.JTextArea();
        NombreT = new javax.swing.JTextField();
        GarantiaT = new javax.swing.JTextField();
        BuscarCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("BUSCAR PRODUCTO(S)");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 40));

        BuscarBB.setBackground(new java.awt.Color(102, 102, 255));
        BuscarBB.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BuscarBB.setForeground(new java.awt.Color(0, 0, 0));
        BuscarBB.setText("BUSCAR PRODUCTO");
        BuscarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBBActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        VOLVER.setBackground(new java.awt.Color(255, 51, 51));
        VOLVER.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VOLVER.setForeground(new java.awt.Color(0, 0, 0));
        VOLVER.setText("VOLVER");
        VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID     NOMBRE      PRECIO      STOCK      MARCA      ORIGEN      CATEGORIA       CODIGO         GARANTIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 670, 30));

        MostrarT.setColumns(20);
        MostrarT.setRows(5);
        getContentPane().add(MostrarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 680, 330));

        NombreT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        NombreT.setForeground(new java.awt.Color(0, 0, 0));
        NombreT.setAutoscrolls(false);
        NombreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTActionPerformed(evt);
            }
        });
        getContentPane().add(NombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, -1));

        GarantiaT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GarantiaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GarantiaTActionPerformed(evt);
            }
        });
        getContentPane().add(GarantiaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));

        BuscarCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BuscarCB.setForeground(new java.awt.Color(0, 0, 0));
        BuscarCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE", "GARANTIA" }));
        BuscarCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCBActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Modo de buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Garantia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/fondos.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 720, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBBActionPerformed
        int opcion = BuscarCB.getSelectedIndex();
        if (!(NombreT.getText().equals("") || GarantiaT.getText().equals(""))) {
            switch (opcion) {
            case 0:
                String nombre = NombreT.getText();
                buscarNombre(nombre);
                break;
            case 1:
                int garantia = Integer.parseInt(GarantiaT.getText());
                buscarGarantia(garantia);
                break;
            default:
                JOptionPane.showMessageDialog(null, "< OPCION INVALIDA ");
        }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR: CUADRO EN BLANCO");
        }
    }//GEN-LAST:event_BuscarBBActionPerformed

    public String darformato_decimal(float decimal, int max) {
        return String.format("%-" + max + ".2f", decimal);
    }

    public String darformato_entero(int entero, int max) {
        return String.format("%-" + max + "d", entero);
    }

    public String darformato_cadena(String cadena, int max) {
        if (cadena == null) {
            cadena = "";
        }
        if (cadena.length() >= max) {
            return cadena.substring(0, max - 3) + "..";
        } else {
            return String.format("%-" + max + "s", cadena);
        }
    }

    public void buscarNombre(String nombre) {
        MostrarT.setText(""); //Aca lo limpie pero en plan regreso al menu y vuelvo a listar y se duplica ;(
        int contador = 0;
        if (contador>0) {
            for (int i = 0; i < Ferreteria.cantidad; i++) {
                if (Ferreteria.nombre[i].contains(nombre)) {
                    contador++;
                    MostrarT.append(darformato_cadena(contador + "        " + Ferreteria.nombre[i], 18) + "\t         "
                            + darformato_decimal(Ferreteria.precio[i], 10) + "\t    "
                            + darformato_entero(Ferreteria.stock[i], 7) + "\t"
                            + darformato_cadena(Ferreteria.marca[i], 8) + "\t"
                            + darformato_cadena(Ferreteria.origen[i], 10) + "\t"
                            + darformato_cadena(Ferreteria.categoría[i], 12) + "\t"
                            + darformato_cadena(Ferreteria.código[i], 11) + "\t"
                            + darformato_entero(Ferreteria.garantía[i], 5) + "\n");

                } else {
                    JOptionPane.showMessageDialog(null, "< NO HAY PRODUCTOS PARA LISTAR >");
                }
            }
        }
    }
    
    public void buscarGarantia(int garantia) {
        MostrarT.setText(""); //Aca lo limpie pero en plan regreso al menu y vuelvo a listar y se duplica ;(
        int contador = 0;
        if (contador>0) {
            for (int i = 0; i < Ferreteria.cantidad; i++) {
                if (Ferreteria.garantía[i] == garantia) {
                    contador++;
                    MostrarT.append(darformato_cadena(contador + "        " + Ferreteria.nombre[i], 18) + "\t         "
                            + darformato_decimal(Ferreteria.precio[i], 10) + "\t    "
                            + darformato_entero(Ferreteria.stock[i], 7) + "\t"
                            + darformato_cadena(Ferreteria.marca[i], 8) + "\t"
                            + darformato_cadena(Ferreteria.origen[i], 10) + "\t"
                            + darformato_cadena(Ferreteria.categoría[i], 12) + "\t"
                            + darformato_cadena(Ferreteria.código[i], 11) + "\t"
                            + darformato_entero(Ferreteria.garantía[i], 5) + "\n");

                } else {
                    JOptionPane.showMessageDialog(null, "< NO HAY PRODUCTOS PARA LISTAR >");
                }
            }
        }
    }
    private void VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERActionPerformed
        Ferreteria ferreteria = new Ferreteria();
        ferreteria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VOLVERActionPerformed

    private void NombreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTActionPerformed

    private void GarantiaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GarantiaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GarantiaTActionPerformed

    private void BuscarCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBB;
    private javax.swing.JComboBox<String> BuscarCB;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField GarantiaT;
    private javax.swing.JTextArea MostrarT;
    private javax.swing.JTextField NombreT;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
