/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_netbeans;

import javax.swing.JOptionPane;

/**
 *
 * @author Lee Brandon
 */
public class JFEditar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public JFEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        EditarBB = new javax.swing.JButton();
        VOLVER = new javax.swing.JButton();
        MostrarBB = new javax.swing.JButton();
        MostrarT = new javax.swing.JTextArea();
        Nombre = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Origen = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        Garantia = new javax.swing.JLabel();
        NombreT = new javax.swing.JTextField();
        PrecioT = new javax.swing.JTextField();
        StockT = new javax.swing.JTextField();
        MarcaT = new javax.swing.JTextField();
        OrigenT = new javax.swing.JTextField();
        CategoriaCB = new javax.swing.JComboBox<>();
        CodigoT = new javax.swing.JTextField();
        GarantiaT = new javax.swing.JTextField();
        Posicion = new javax.swing.JLabel();
        PosicionT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("EDITAR PRODUCTO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 40));

        EditarBB.setBackground(new java.awt.Color(102, 102, 255));
        EditarBB.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EditarBB.setForeground(new java.awt.Color(0, 0, 0));
        EditarBB.setText("EDITAR PRODUCTO");
        EditarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBBActionPerformed(evt);
            }
        });
        getContentPane().add(EditarBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, -1, -1));

        VOLVER.setBackground(new java.awt.Color(255, 51, 51));
        VOLVER.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VOLVER.setForeground(new java.awt.Color(0, 0, 0));
        VOLVER.setText("VOLVER");
        VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 150, -1));

        MostrarBB.setBackground(new java.awt.Color(204, 255, 204));
        MostrarBB.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        MostrarBB.setForeground(new java.awt.Color(0, 0, 0));
        MostrarBB.setText("MOSTRAR");
        MostrarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBBActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, -1, -1));

        MostrarT.setColumns(20);
        MostrarT.setRows(5);
        getContentPane().add(MostrarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 680, 360));

        Nombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nuevo Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        Precio.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Precio.setForeground(new java.awt.Color(0, 0, 0));
        Precio.setText("Nuevo Precio  (S/)");
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        Stock.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Stock.setForeground(new java.awt.Color(0, 0, 0));
        Stock.setText("Nuevo Stock");
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        Marca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Marca.setForeground(new java.awt.Color(0, 0, 0));
        Marca.setText("Nueva Marca");
        getContentPane().add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        Origen.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Origen.setForeground(new java.awt.Color(0, 0, 0));
        Origen.setText("Nuevo Origen");
        getContentPane().add(Origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 30));

        Categoria.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Categoria.setForeground(new java.awt.Color(0, 0, 0));
        Categoria.setText("Nueva Categoria");
        getContentPane().add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 30));

        Codigo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Codigo.setForeground(new java.awt.Color(0, 0, 0));
        Codigo.setText("Nuevo Codigo");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, 30));

        Garantia.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Garantia.setForeground(new java.awt.Color(0, 0, 0));
        Garantia.setText("Nueva Garantia (meses)");
        getContentPane().add(Garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 190, 30));

        NombreT.setBackground(new java.awt.Color(204, 204, 255));
        NombreT.setForeground(new java.awt.Color(0, 0, 0));
        NombreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTActionPerformed(evt);
            }
        });
        getContentPane().add(NombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, -1));

        PrecioT.setBackground(new java.awt.Color(204, 204, 255));
        PrecioT.setForeground(new java.awt.Color(0, 0, 0));
        PrecioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTActionPerformed(evt);
            }
        });
        getContentPane().add(PrecioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, -1));

        StockT.setBackground(new java.awt.Color(204, 204, 255));
        StockT.setForeground(new java.awt.Color(0, 0, 0));
        StockT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockTActionPerformed(evt);
            }
        });
        getContentPane().add(StockT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, -1));

        MarcaT.setBackground(new java.awt.Color(204, 204, 255));
        MarcaT.setForeground(new java.awt.Color(0, 0, 0));
        MarcaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaTActionPerformed(evt);
            }
        });
        getContentPane().add(MarcaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, -1));

        OrigenT.setBackground(new java.awt.Color(204, 204, 255));
        OrigenT.setForeground(new java.awt.Color(0, 0, 0));
        OrigenT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrigenTActionPerformed(evt);
            }
        });
        getContentPane().add(OrigenT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 180, -1));

        CategoriaCB.setBackground(new java.awt.Color(204, 204, 255));
        CategoriaCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CategoriaCB.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Herramientas", "Construcción", "Pinturas", "Electricidad", "Seguridad", "Jardín", "Accesorios", "Otros" }));
        CategoriaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaCBActionPerformed(evt);
            }
        });
        getContentPane().add(CategoriaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 180, -1));

        CodigoT.setBackground(new java.awt.Color(204, 204, 255));
        CodigoT.setForeground(new java.awt.Color(0, 0, 0));
        CodigoT.setCaretColor(new java.awt.Color(0, 0, 0));
        CodigoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 180, -1));

        GarantiaT.setBackground(new java.awt.Color(204, 204, 255));
        GarantiaT.setForeground(new java.awt.Color(0, 0, 0));
        GarantiaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GarantiaTActionPerformed(evt);
            }
        });
        getContentPane().add(GarantiaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 150, -1));

        Posicion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        Posicion.setForeground(new java.awt.Color(0, 0, 0));
        Posicion.setText("Posicion");
        getContentPane().add(Posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, 30));

        PosicionT.setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().add(PosicionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID     NOMBRE      PRECIO      STOCK      MARCA      ORIGEN      CATEGORIA       CODIGO         GARANTIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 670, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/fondos.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 720, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/fondos.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 540, 720, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String darformato_decimal(float decimal, int max) {
        return String.format("%-" + max + ".2f", decimal);
    }

    public String darformato_entero(int entero, int max) {
        return String.format("%-" + max + "d", entero);
    }

    public String darformato_cadena(String cadena, int max) {
        if (cadena == null) {
            cadena = "";
        }
        if (cadena.length() >= max) {
            return cadena.substring(0, max - 3) + "..";
        } else {
            return String.format("%-" + max + "s", cadena);
        }
    }
    public boolean ochoDigitos (String codigo){
        return codigo.matches("\\d{8}");
    }
    public void Mostrar() {
        MostrarT.setText("");
        int contador = 0;
        if (contador>0) {
            for (int i = 0; i < Ferreteria.cantidad; i++) {
                contador++;
                MostrarT.append(darformato_cadena(contador + "        " + Ferreteria.nombre[i], 15) + "\t         "
                        + darformato_decimal(Ferreteria.precio[i], 10) + "\t    "
                        + darformato_entero(Ferreteria.stock[i], 7) + "\t"
                        + darformato_cadena(Ferreteria.marca[i], 8) + "\t"
                        + darformato_cadena(Ferreteria.origen[i], 10) + "\t"
                        + darformato_cadena(Ferreteria.categoría[i], 12) + "\t"
                        + darformato_cadena(Ferreteria.código[i], 11) + "\t"
                        + darformato_entero(Ferreteria.garantía[i], 5) + "\n");
            }
        } else {
            JOptionPane.showMessageDialog(null, "< NO HAY PRODUCTOS PARA LISTAR >");
        }
    }

    public void editar(int pos, String nombre, float precio, int stock, String marca, String origen, int opcion, String codigo, int garantia) {
        pos--;
        opcion = CategoriaCB.getSelectedIndex();
        String categoria = "";
        switch (opcion) {
            case 0 -> categoria = "Herramientas";
            case 1 -> categoria = "Construcción";
            case 2 -> categoria = "Pinturas";
            case 3 -> categoria = "Electricidad";
            case 4 -> categoria = "Seguridad";
            case 5 -> categoria = "Jardin";
            case 6 -> categoria = "Accesorios";
            case 7 -> categoria = "Otros";
            default -> JOptionPane.showMessageDialog(null, "< OPCION INVALIDA >");
        }
        Ferreteria.nombre[pos] = nombre;
        Ferreteria.precio[pos] = precio;
        Ferreteria.stock[pos] = stock;
        Ferreteria.marca[pos] = marca;
        Ferreteria.origen[pos] = origen;
        Ferreteria.categoría[pos] = categoria;
        Ferreteria.código[pos] = codigo;
        Ferreteria.garantía[pos] = garantia;
        
    }
    private void EditarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBBActionPerformed
        int posicion = Integer.parseInt(PosicionT.getText());
        if (!(NombreT.getText().equals("") || PrecioT.getText().equals("") || StockT.getText().equals("") || MarcaT.getText().equals("") || OrigenT.getText().equals("") || CodigoT.getText().equals("") || GarantiaT.getText().equals(""))) {
            try {
                String nombre = NombreT.getText();
                float precio = Float.parseFloat(PrecioT.getText());
                int stock = Integer.parseInt(StockT.getText());
                String marca = MarcaT.getText();
                String origen = OrigenT.getText();
                String codigo = CodigoT.getText();
                int garantia = Integer.parseInt(GarantiaT.getText());
                int opcion = CategoriaCB.getSelectedIndex();
                editar(posicion, nombre, precio, stock, marca, origen, opcion, codigo, garantia);
                 //Metodo editar, nop 
                if (ochoDigitos(codigo)) {
                    JOptionPane.showMessageDialog(null, "< AGREGADO CORRECTAMENTE >");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "< ERROR: FORMATO NUMERICO INVALIDO >");
            }
        } else {
            JOptionPane.showMessageDialog(null, "< ERROR: CAMPO VACIO >");
        }//Osea los datos agregados manialmente se duplican no se poruqe

    }//GEN-LAST:event_EditarBBActionPerformed

    private void VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERActionPerformed
        Ferreteria ferreteria = new Ferreteria();
        ferreteria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VOLVERActionPerformed

    private void MostrarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBBActionPerformed
        Mostrar();
    }//GEN-LAST:event_MostrarBBActionPerformed

    private void NombreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTActionPerformed

    private void PrecioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTActionPerformed

    private void StockTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockTActionPerformed

    private void MarcaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaTActionPerformed

    private void OrigenTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrigenTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrigenTActionPerformed

    private void CategoriaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaCBActionPerformed

    private void CodigoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTActionPerformed

    private void GarantiaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GarantiaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GarantiaTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JComboBox<String> CategoriaCB;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField CodigoT;
    private javax.swing.JButton EditarBB;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Garantia;
    private javax.swing.JTextField GarantiaT;
    private javax.swing.JLabel Marca;
    private javax.swing.JTextField MarcaT;
    private javax.swing.JButton MostrarBB;
    private javax.swing.JTextArea MostrarT;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreT;
    private javax.swing.JLabel Origen;
    private javax.swing.JTextField OrigenT;
    private javax.swing.JLabel Posicion;
    private javax.swing.JTextField PosicionT;
    private javax.swing.JLabel Precio;
    private javax.swing.JTextField PrecioT;
    private javax.swing.JLabel Stock;
    private javax.swing.JTextField StockT;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
