/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_netbeans;

import javax.swing.JOptionPane;

/**
 *
 * @author Lee Brandon
 */
public class JFEliminar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public JFEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        EliminarBB = new javax.swing.JButton();
        VOLVER = new javax.swing.JButton();
        MostrarBB = new javax.swing.JButton();
        MostrarT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        PosicionL = new javax.swing.JLabel();
        PosicionT = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("ELIMINAR PRODUCTO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 40));

        EliminarBB.setBackground(new java.awt.Color(102, 102, 255));
        EliminarBB.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EliminarBB.setForeground(new java.awt.Color(0, 0, 0));
        EliminarBB.setText("ELIMINAR PRODUCTO");
        EliminarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBBActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        VOLVER.setBackground(new java.awt.Color(255, 51, 51));
        VOLVER.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VOLVER.setForeground(new java.awt.Color(0, 0, 0));
        VOLVER.setText("VOLVER");
        VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 150, -1));

        MostrarBB.setBackground(new java.awt.Color(204, 255, 204));
        MostrarBB.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        MostrarBB.setForeground(new java.awt.Color(0, 0, 0));
        MostrarBB.setText("MOSTRAR");
        MostrarBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBBActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        MostrarT.setColumns(20);
        MostrarT.setRows(5);
        getContentPane().add(MostrarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 680, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID     NOMBRE      PRECIO      STOCK      MARCA      ORIGEN      CATEGORIA       CODIGO         GARANTIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 670, 30));

        PosicionL.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        PosicionL.setForeground(new java.awt.Color(0, 0, 0));
        PosicionL.setText("INDIQUE POSICION:");
        getContentPane().add(PosicionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        PosicionT.setBackground(new java.awt.Color(204, 204, 204));
        PosicionT.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(PosicionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 400, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_imagenes/fondos.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String darformato_decimal(float decimal, int max) {
        return String.format("%-" + max + ".2f", decimal);
    }

    public String darformato_entero(int entero, int max) {
        return String.format("%-" + max + "d", entero);
    }

    public String darformato_cadena(String cadena, int max) {
        if (cadena == null) {
            cadena = "";
        }
        if (cadena.length() >= max) {
            return cadena.substring(0, max - 3) + "..";
        } else {
            return String.format("%-" + max + "s", cadena);
        }
    }

    public void eliminar(int posicion) {
        posicion--;
        if (!PosicionT.getText().equals("")) {
            for (int i = posicion; i < Ferreteria.cantidad; i++) {
                Ferreteria.nombre[i] = Ferreteria.nombre[i + 1];
                Ferreteria.precio[i] = Ferreteria.precio[i + 1];
                Ferreteria.stock[i] = Ferreteria.stock[i + 1];
                Ferreteria.marca[i] = Ferreteria.marca[i + 1];
                Ferreteria.origen[i] = Ferreteria.origen[i + 1];
                Ferreteria.categoría[i] = Ferreteria.categoría[i + 1];
                Ferreteria.código[i] = Ferreteria.código[i + 1];
                Ferreteria.garantía[i] = Ferreteria.garantía[i + 1];
            }
            Ferreteria.nombre[Ferreteria.cantidad] = null;
            Ferreteria.precio[Ferreteria.cantidad] = 0;
            Ferreteria.stock[Ferreteria.cantidad] = 0;
            Ferreteria.marca[Ferreteria.cantidad] = null;
            Ferreteria.origen[Ferreteria.cantidad] = null;
            Ferreteria.categoría[Ferreteria.cantidad] = null;
            Ferreteria.código[Ferreteria.cantidad] = null;
            Ferreteria.garantía[Ferreteria.cantidad] = 0;
            Ferreteria.cantidad--;
            JOptionPane.showMessageDialog(null, "< ELIMINADO CORRECTAMENTE >");
        } else {
            JOptionPane.showMessageDialog(null, "< ERROR: ESPACIO EN BLANCO >");
        }
    }

    public void Mostrar() {
        MostrarT.setText("");
        int contador = 0;
        if (Ferreteria.nombre!=null || Ferreteria.nombre.length>0) {
            for (int i = 0; i < Ferreteria.cantidad; i++) {
            contador++;
            MostrarT.append(darformato_cadena(contador + "        " + Ferreteria.nombre[i], 18) + "\t         "
                    + darformato_decimal(Ferreteria.precio[i], 10) + "\t    "
                    + darformato_entero(Ferreteria.stock[i], 7) + "\t"
                    + darformato_cadena(Ferreteria.marca[i], 8) + "\t"
                    + darformato_cadena(Ferreteria.origen[i], 10) + "\t"
                    + darformato_cadena(Ferreteria.categoría[i], 12) + "\t"
                    + darformato_cadena(Ferreteria.código[i], 11) + "\t"
                    + darformato_entero(Ferreteria.garantía[i], 5) + "\n");
        }
        } else {
            JOptionPane.showMessageDialog(null, "< NO HAY PRODUCTOS PARA LISTAR >");
        }
    }
    private void EliminarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBBActionPerformed
        int posicion = Integer.parseInt(PosicionT.getText());
        eliminar(posicion);
    }//GEN-LAST:event_EliminarBBActionPerformed


    private void MostrarBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBBActionPerformed
        Mostrar();
    }//GEN-LAST:event_MostrarBBActionPerformed

    private void VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERActionPerformed
        Ferreteria ferreteria = new Ferreteria();
        ferreteria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VOLVERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarBB;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton MostrarBB;
    private javax.swing.JTextArea MostrarT;
    private javax.swing.JLabel PosicionL;
    private javax.swing.JTextField PosicionT;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
